# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=8000"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        "types_or": [python, pyi]
        exclude: ^(tests|notebook/Projects/Retriever/pdf-chatbot)
        args:
          [
            "--ignore-missing-imports",
            "--disallow-any-generics",
            "--config-file",
            "./pyproject.toml",
          ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        exclude: ^(notebook/Projects/Retriever/pdf-chatbot)/  # Exclude multiple dirs
      # Run the formatter.
      - id: ruff-format
